Add disasm functionarity

diff --git a/boxes/base/script b/boxes/base/script
--- a/boxes/base/script
+++ b/boxes/base/script
@@ -5,6 +5,15 @@ if ! [ -e /root/script ]; then
   exit 1
 fi
 
+if [ "$#" = 2 ] && [ "$1" = "-d" ]; then
+  if ! [ -e /root/disasm ]; then
+    echo "esolang-box: [ERROR] Disassembly is not supported for this language" >&2
+    exit 1
+  fi
+  /bin/sh /root/disasm "$2"
+  exit 0
+fi
+
 if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
   echo "Usage: $0 <file>" >&2
   exit 1
